# Generated by Django 5.0.1 on 2025-12-24 09:41

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('excerpt', models.TextField(blank=True, help_text='Brief description of the article', max_length=500)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, help_text='SEO meta title (max 60 chars, leave blank to use article title)', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description (max 160 chars)', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords for SEO', max_length=255)),
                ('og_title', models.CharField(blank=True, help_text='Open Graph title (leave blank to use meta_title or title)', max_length=95)),
                ('og_description', models.CharField(blank=True, help_text='Open Graph description', max_length=200)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
                ('featured_image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_featured_image', to=settings.FILER_IMAGE_MODEL)),
                ('og_image', filer.fields.image.FilerImageField(blank=True, help_text='Image for social media sharing (leave blank to use featured_image)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_og_image', to=settings.FILER_IMAGE_MODEL)),
                ('categories', models.ManyToManyField(blank=True, related_name='articles', to='articles.category')),
            ],
            options={
                'ordering': ['-published_date', '-created_at'],
                'indexes': [models.Index(fields=['-published_date'], name='articles_ar_publish_35dcc3_idx'), models.Index(fields=['slug'], name='articles_ar_slug_452037_idx'), models.Index(fields=['status'], name='articles_ar_status_edb746_idx')],
            },
        ),
    ]
